


//**************CLASS BY COURSE*************************
//lay lop hop từ khóa học
export const GET_CLASS_BY_COURSE = 'GET_CLASS_BY_COURSE'
export const GET_CLASS_BY_COURSE_SUCCESS = 'GET_CLASS_BY_COURSE_SUCCESS'
export const GET_CLASS_BY_COURSE_ERROR = 'GET_CLASS_BY_COURSE_ERROR'

//them lop hop từ khóa học
export const ADD_CLASS_BY_COURSE = 'ADD_CLASS_BY_COURSE'
export const ADD_CLASS_BY_COURSE_SUCCESS = 'ADD_CLASS_BY_COURSE_SUCCESS'
export const ADD_CLASS_BY_COURSE_ERROR = 'ADD_CLASS_BY_COURSE_ERROR'

//them lop hop từ khóa học
export const DELETE_CLASS_BY_COURSE = 'DELETE_CLASS_BY_COURSE'
export const DELETE_CLASS_BY_COURSE_SUCCESS = 'DELETE_CLASS_BY_COURSE_SUCCESS'
export const DELETE_CLASS_BY_COURSE_ERROR = 'DELETE_CLASS_BY_COURSE_ERROR'

//cap nhat lop hop từ khóa học
export const UPDATE_CLASS_BY_COURSE = 'UPDATE_CLASS_BY_COURSE'
export const UPDATE_CLASS_BY_COURSE_SUCCESS = 'UPDATE_CLASS_BY_COURSE_SUCCESS'
export const UPDATE_CLASS_BY_COURSE_ERROR = 'UPDATE_CLASS_BY_COURSE_ERROR'
