export const DRAWER_SCREEN='DRAWER_SCREEN';
export const LOGIN_SCREEN='LOGIN_SCREEN';
export const ADD_COURSE='ADD_COURSE';
export const SCHEDULE_COURSE='SCHEDULE_COURSE';
export const ADD_SCHEDULE_COURSE='ADD_SCHEDULE_COURSE';
export const TICKET='TICKET';
